alembic==1.7.5
APScheduler==3.6.3
behave==1.2.6
cachetools==4.2.2
cachier==1.5.3
certifi==2021.10.8
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
Flask==2.0.2
Flask-Cors==3.0.10
Flask-Ext==0.1
flask-marshmallow==0.14.0
Flask-Migrate==3.1.0
Flask-SQLAlchemy==2.5.1
greenlet==1.1.2
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
JzStock==0.2
loguru==0.5.3
Mako==1.1.6
MarkupSafe==2.0.1
marshmallow==3.14.1
migrate==0.3.7
packaging==21.3
parse==1.19.0
parse-type==0.5.2
pathtools==0.1.2
plumbum==1.7.1
portalocker==2.3.2
psycopg2==2.9.2
py-bcrypt==0.4
pycryptodome==3.12.0
pymongo==3.12.1
pyparsing==3.0.6
pypiwin32==223
python-rex==0.4
python-telegram-bot==13.9
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
pywin32==303
PyYAML==5.4.1
requests==2.26.0
rncryptor==3.3.0
six==1.16.0
SQLAlchemy==1.4.29
SQLAlchemy-Utils==0.38.2
telegram==0.0.1
tornado==6.1
tzdata==2021.5
tzlocal==4.1
#updater==0.3.2
urllib3==1.26.7
watchdog==2.1.6
Werkzeug==2.0.2
win32-setctime==1.0.4
